In [1]:
# Importando bibliotecas que vou usar
import os
import glob
import pandas as pd
import chardet
import haversine as hs
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

In [2]:
#Selecionando o diretório de dados (onde está cada arquivo .csv)
os.chdir("C:\\Users\\joaov\\Desktop\\Torres Consolidado\\Extração de Torres e Escola CSV")
extension = 'csv'
all_filenames = [i for i in glob.glob('*.{}'.format(extension))]

In [3]:
#Encontrando o enconding correto
#rawdata = open('1.csv', "rb").read()
#chardet.detect(rawdata)

In [4]:
#Consolidando todas as bases
combined_csv = pd.concat([pd.read_csv(f, encoding="ISO-8859-1") for f in all_filenames ])

C:\Users\joaov\AppData\Local\Temp\ipykernel_18260\2395269944.py:2: DtypeWarning: Columns (7,11,12,16,18,19,20,21,22,23,24,25,27,28,29,33,35,39) have mixed types. Specify dtype option on import or set low_memory=False.
  combined_csv = pd.concat([pd.read_csv(f, encoding="ISO-8859-1") for f in all_filenames ])
C:\Users\joaov\AppData\Local\Temp\ipykernel_18260\2395269944.py:2: DtypeWarning: Columns (16,18,19,21,22,24,25,28,29,35) have mixed types. Specify dtype option on import or set low_memory=False.
  combined_csv = pd.concat([pd.read_csv(f, encoding="ISO-8859-1") for f in all_filenames ])
C:\Users\joaov\AppData\Local\Temp\ipykernel_18260\2395269944.py:2: DtypeWarning: Columns (5,7,9,11,12,14,15,16,18,19,20,21,22,23,24,25,27,28,29,33,35,39) have mixed types. Specify dtype option on import or set low_memory=False.
  combined_csv = pd.concat([pd.read_csv(f, encoding="ISO-8859-1") for f in all_filenames ])
C:\Users\joaov\AppData\Local\Temp\ipykernel_18260\2395269944.py:2: DtypeWarning: Columns (5,7,11,12,16,18,19,21,22,24,25,27,28,29,35,39) have mixed types. Specify dtype option on import or set low_memory=False.
  combined_csv = pd.concat([pd.read_csv(f, encoding="ISO-8859-1") for f in all_filenames ])
C:\Users\joaov\AppData\Local\Temp\ipykernel_18260\2395269944.py:2: DtypeWarning: Columns (16,18,19,23,24,25,27,29) have mixed types. Specify dtype option on import or set low_memory=False.
  combined_csv = pd.concat([pd.read_csv(f, encoding="ISO-8859-1") for f in all_filenames ])
C:\Users\joaov\AppData\Local\Temp\ipykernel_18260\2395269944.py:2: DtypeWarning: Columns (7,11,12,16,18,19,21,22,24,25,29,30,31,35,39) have mixed types. Specify dtype option on import or set low_memory=False.
  combined_csv = pd.concat([pd.read_csv(f, encoding="ISO-8859-1") for f in all_filenames ])
C:\Users\joaov\AppData\Local\Temp\ipykernel_18260\2395269944.py:2: DtypeWarning: Columns (7,11,12,16,18,19,21,22,23,24,25,27,28,29,35,39) have mixed types. Specify dtype option on import or set low_memory=False.
  combined_csv = pd.concat([pd.read_csv(f, encoding="ISO-8859-1") for f in all_filenames ])
C:\Users\joaov\AppData\Local\Temp\ipykernel_18260\2395269944.py:2: DtypeWarning: Columns (7,11,12,16,18,19,21,22,23,24,25,27,28,29,35,39) have mixed types. Specify dtype option on import or set low_memory=False.
  combined_csv = pd.concat([pd.read_csv(f, encoding="ISO-8859-1") for f in all_filenames ])
C:\Users\joaov\AppData\Local\Temp\ipykernel_18260\2395269944.py:2: DtypeWarning: Columns (12,16,18,19,20,22,23,24,25,27,28,29,35,39) have mixed types. Specify dtype option on import or set low_memory=False.
  combined_csv = pd.concat([pd.read_csv(f, encoding="ISO-8859-1") for f in all_filenames ])
C:\Users\joaov\AppData\Local\Temp\ipykernel_18260\2395269944.py:2: DtypeWarning: Columns (7,11,12,18,19,21,22,28,29,35,39) have mixed types. Specify dtype option on import or set low_memory=False.
  combined_csv = pd.concat([pd.read_csv(f, encoding="ISO-8859-1") for f in all_filenames ])
C:\Users\joaov\AppData\Local\Temp\ipykernel_18260\2395269944.py:2: DtypeWarning: Columns (7,11,12,16,18,19,21,22,23,24,25,28,29,35,39) have mixed types. Specify dtype option on import or set low_memory=False.
  combined_csv = pd.concat([pd.read_csv(f, encoding="ISO-8859-1") for f in all_filenames ])
C:\Users\joaov\AppData\Local\Temp\ipykernel_18260\2395269944.py:2: DtypeWarning: Columns (7,11,12,16,18,19,20,21,22,23,24,25,27,28,29,30,31,35) have mixed types. Specify dtype option on import or set low_memory=False.
  combined_csv = pd.concat([pd.read_csv(f, encoding="ISO-8859-1") for f in all_filenames ])
C:\Users\joaov\AppData\Local\Temp\ipykernel_18260\2395269944.py:2: DtypeWarning: Columns (16,18,19,21,22,23,25,28,29,39) have mixed types. Specify dtype option on import or set low_memory=False.
  combined_csv = pd.concat([pd.read_csv(f, encoding="ISO-8859-1") for f in all_filenames ])
C:\Users\joaov\AppData\Local\Temp\ipykernel_18260\2395269944.py:2: DtypeWarning: Columns (7,11,12,16,18,19,20,21,22,24,25,27,28,29,35,39) have mixed types. Specify dtype option on import or set low_memory=False.
  combined_csv = pd.concat([pd.read_csv(f, encoding="ISO-8859-1") for f in all_filenames ])
C:\Users\joaov\AppData\Local\Temp\ipykernel_18260\2395269944.py:2: DtypeWarning: Columns (12,16,18,19,22,23,24,25,27,29,35,39) have mixed types. Specify dtype option on import or set low_memory=False.
  combined_csv = pd.concat([pd.read_csv(f, encoding="ISO-8859-1") for f in all_filenames ])
C:\Users\joaov\AppData\Local\Temp\ipykernel_18260\2395269944.py:2: DtypeWarning: Columns (29,39) have mixed types. Specify dtype option on import or set low_memory=False.
  combined_csv = pd.concat([pd.read_csv(f, encoding="ISO-8859-1") for f in all_filenames ])
C:\Users\joaov\AppData\Local\Temp\ipykernel_18260\2395269944.py:2: DtypeWarning: Columns (7,11,12,16,18,19,21,22,23,24,25,27,28,29,35,39) have mixed types. Specify dtype option on import or set low_memory=False.
  combined_csv = pd.concat([pd.read_csv(f, encoding="ISO-8859-1") for f in all_filenames ])
C:\Users\joaov\AppData\Local\Temp\ipykernel_18260\2395269944.py:2: DtypeWarning: Columns (7,11,12,18,19,21,22,28,29,35,39) have mixed types. Specify dtype option on import or set low_memory=False.
  combined_csv = pd.concat([pd.read_csv(f, encoding="ISO-8859-1") for f in all_filenames ])
C:\Users\joaov\AppData\Local\Temp\ipykernel_18260\2395269944.py:2: DtypeWarning: Columns (7,11,12,16,18,19,21,22,24,25,28,29,35,39) have mixed types. Specify dtype option on import or set low_memory=False.
  combined_csv = pd.concat([pd.read_csv(f, encoding="ISO-8859-1") for f in all_filenames ])
C:\Users\joaov\AppData\Local\Temp\ipykernel_18260\2395269944.py:2: DtypeWarning: Columns (7,11,12,16,18,19,21,22,23,24,25,27,28,29,35,39) have mixed types. Specify dtype option on import or set low_memory=False.
  combined_csv = pd.concat([pd.read_csv(f, encoding="ISO-8859-1") for f in all_filenames ])
C:\Users\joaov\AppData\Local\Temp\ipykernel_18260\2395269944.py:2: DtypeWarning: Columns (16,21,25,29) have mixed types. Specify dtype option on import or set low_memory=False.
  combined_csv = pd.concat([pd.read_csv(f, encoding="ISO-8859-1") for f in all_filenames ])
C:\Users\joaov\AppData\Local\Temp\ipykernel_18260\2395269944.py:2: DtypeWarning: Columns (7,11,12,16,18,19,21,22,24,25,28,29,35,39) have mixed types. Specify dtype option on import or set low_memory=False.
  combined_csv = pd.concat([pd.read_csv(f, encoding="ISO-8859-1") for f in all_filenames ])
C:\Users\joaov\AppData\Local\Temp\ipykernel_18260\2395269944.py:2: DtypeWarning: Columns (7,11,12,15,16,18,19,20,21,22,23,24,25,27,28,29,35,39) have mixed types. Specify dtype option on import or set low_memory=False.
  combined_csv = pd.concat([pd.read_csv(f, encoding="ISO-8859-1") for f in all_filenames ])
C:\Users\joaov\AppData\Local\Temp\ipykernel_18260\2395269944.py:2: DtypeWarning: Columns (7,11,12,16,18,19,21,22,23,24,25,27,28,29,30,31,35,39) have mixed types. Specify dtype option on import or set low_memory=False.
  combined_csv = pd.concat([pd.read_csv(f, encoding="ISO-8859-1") for f in all_filenames ])
C:\Users\joaov\AppData\Local\Temp\ipykernel_18260\2395269944.py:2: DtypeWarning: Columns (7,11,12,16,18,19,20,21,22,23,24,25,28,29,35,39) have mixed types. Specify dtype option on import or set low_memory=False.
  combined_csv = pd.concat([pd.read_csv(f, encoding="ISO-8859-1") for f in all_filenames ])

In [5]:
#Transformando FreqTxMHz em float, ele vem como object
combined_csv['FreqTxMHz'] = combined_csv['FreqTxMHz'].astype(float)

In [6]:
#Dataframe resultante
combined_csv

,Status.state,NomeEntidade,NumFistel,NumServico,NumAto,NumEstacao,EnderecoEstacao,EndComplemento,SiglaUf,CodMunicipio,...,Latitude,Longitude,CodDebitoTFI,DataLicenciamento,DataPrimeiroLicenciamento,NumRede,_id,DataValidade,NumFistelAssociado,NomeEntidadeAssociado
0,LIC-LIC-01,TELEFONICA BRASIL S.A.,5.040915e+10,10.0,48412023.0,5202620,RUA DE CATUMBI,NaN,RJ,3304557,...,-22.91667,-43.19444,G,2023-07-05,1999-09-15,NaN,4d5c019f69f36,2038-04-30,NaN,NaN
1,LIC-LIC-01,TELEFONICA BRASIL S.A.,5.040915e+10,10.0,48412023.0,5202620,RUA DE CATUMBI,NaN,RJ,3304557,...,-22.91667,-43.19444,G,2023-07-05,1999-09-15,NaN,4d5c019f69f37,2038-04-30,NaN,NaN
2,LIC-LIC-01,TELEFONICA BRASIL S.A.,5.040915e+10,10.0,48422023.0,5202620,RUA DE CATUMBI,NaN,RJ,3304557,...,-22.91667,-43.19444,G,2023-07-05,1999-09-15,NaN,4d5c019f69f38,2038-04-30,NaN,NaN
3,LIC-LIC-01,TELEFONICA BRASIL S.A.,5.040915e+10,10.0,48422023.0,5202620,RUA DE CATUMBI,NaN,RJ,3304557,...,-22.91667,-43.19444,G,2023-07-05,1999-09-15,NaN,4d5c019f69f39,2038-04-30,NaN,NaN
4,LIC-LIC-01,TELEFONICA BRASIL S.A.,5.040915e+10,10.0,48412023.0,5202620,RUA DE CATUMBI,NaN,RJ,3304557,...,-22.91667,-43.19444,G,2023-07-05,1999-09-15,NaN,4d5c019f69f3a,2038-04-30,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
320847,LIC-LIC-01,TIM S A,5.040943e+10,10.0,48352023.0,693208287,RUA 11,QD 35,MA,2111201,...,-2.555861,-44.185833,G,2023-10-10,2011-02-22,NaN,b67285f80339dc0c,2029-12-08,NaN,NaN
320848,LIC-LIC-01,TIM S A,5.040943e+10,10.0,48352023.0,693208287,RUA 11,QD 35,MA,2111201,...,-2.555861,-44.185833,G,2023-10-10,2011-02-22,NaN,b67285f80339dc0d,2029-12-08,NaN,NaN
320849,LIC-LIC-01,TIM S A,5.040943e+10,10.0,47102015.0,693208287,RUA 11,QD 35,MA,2111201,...,-2.555861,-44.185833,G,2023-10-10,2011-02-22,NaN,b67285f80339dc0e,2029-12-08,NaN,NaN
320850,LIC-LIC-01,TIM S A,5.040943e+10,10.0,47102015.0,693208287,RUA 11,QD 35,MA,2111201,...,-2.555861,-44.185833,G,2023-10-10,2011-02-22,NaN,b67285f80339dc0f,2029-12-08,NaN,NaN
320851,LIC-LIC-01,TIM S A,5.040943e+10,10.0,47102015.0,693208287,RUA 11,QD 35,MA,2111201,...,-2.555861,-44.185833,G,2023-10-10,2011-02-22,NaN,b67285f80339dc10,2029-12-08,NaN,NaN

In [7]:
#Criando a função para calcular a diferencia em quilômetros
def calc_km(lat1,lon1,lat2,lon2):
    try:
        loc1=(lat1,lon1)
        loc2=(lat2,lon2)
        return hs.haversine(loc1,loc2)
    except:
        pass

In [8]:
#DF de torres filtrando LTE (4G) e o estado
df_torres = combined_csv.loc[(combined_csv['Tecnologia'] == 'LTE') & (combined_csv['FreqTxMHz'] >= 758) & (combined_csv['FreqTxMHz'] <= 894) & (combined_csv['SiglaUf'] == 'PA')]
#DF de escolas filtrando o estado
df_escolas = combined_csv.loc[(combined_csv['Tecnologia'] == 'Escola') & (combined_csv['SiglaUf'] == 'PA')]

In [295]:
#Consolidando os dois dataframes para ter 4 colunas (latitude e longitude torre + latitude e longitude escola)
escola_torre_df = df_torres.merge(df_escolas, how='cross')

In [296]:
#Criando a coluna de distância entre a torre a escola usando haversine
escola_torre_df['Distancia KM'] = escola_torre_df.apply(lambda x:calc_km(x['Latitude_x'], x['Longitude_x'],x['Latitude_y'], x['Longitude_y']), axis=1)

In [297]:
#Dataframe pegando a distância mínima por de escola para torre
escola_torre_df_formatado = escola_torre_df.groupby('NomeEntidade_y').agg({'Distancia KM':[min]}).reset_index()

In [298]:
#Criando a flag "Cobertura" onde <= 35km não tem cobertura
escola_torre_df_formatado['Cobertura'] = np.where(escola_torre_df_formatado['Distancia KM'] <= 35, 1, 0)

In [299]:
#Média de cobertura
escola_torre_df_formatado['Cobertura'].mean()

0.7956521739130434

In [300]:
#Gerando arquivo excel com Escola, quilometragem e Flag Cobertura
escola_torre_df_formatado.to_excel("Cobertura Escolas PA.xlsx")