In [1]:
# Importando bibliotecas que vou usar
import os
import glob
import pandas as pd
import chardet
import haversine as hs
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

In [2]:
#Selecionando o diretório de dados (onde está cada arquivo .csv)
os.chdir("C:\\Users\\joaov\\Desktop\\Torres Consolidado\\Extração de Torres e Escola CSV")
extension = 'csv'
all_filenames = [i for i in glob.glob('*.{}'.format(extension))]

In [3]:
#Encontrando o enconding correto
#rawdata = open('1.csv', "rb").read()
#chardet.detect(rawdata)

In [4]:
#Consolidando todas as bases
combined_csv = pd.concat([pd.read_csv(f, encoding="ISO-8859-1") for f in all_filenames ])

C:\Users\joaov\AppData\Local\Temp\ipykernel_13336\2395269944.py:2: DtypeWarning: Columns (7,11,12,16,18,19,20,21,22,23,24,25,27,28,29,33,35,39) have mixed types. Specify dtype option on import or set low_memory=False.
  combined_csv = pd.concat([pd.read_csv(f, encoding="ISO-8859-1") for f in all_filenames ])
C:\Users\joaov\AppData\Local\Temp\ipykernel_13336\2395269944.py:2: DtypeWarning: Columns (16,18,19,21,22,24,25,28,29,35) have mixed types. Specify dtype option on import or set low_memory=False.
  combined_csv = pd.concat([pd.read_csv(f, encoding="ISO-8859-1") for f in all_filenames ])
C:\Users\joaov\AppData\Local\Temp\ipykernel_13336\2395269944.py:2: DtypeWarning: Columns (5,7,9,11,12,14,15,16,18,19,20,21,22,23,24,25,27,28,29,33,35,39) have mixed types. Specify dtype option on import or set low_memory=False.
  combined_csv = pd.concat([pd.read_csv(f, encoding="ISO-8859-1") for f in all_filenames ])
C:\Users\joaov\AppData\Local\Temp\ipykernel_13336\2395269944.py:2: DtypeWarning: Columns (5,7,11,12,16,18,19,21,22,24,25,27,28,29,35,39) have mixed types. Specify dtype option on import or set low_memory=False.
  combined_csv = pd.concat([pd.read_csv(f, encoding="ISO-8859-1") for f in all_filenames ])
C:\Users\joaov\AppData\Local\Temp\ipykernel_13336\2395269944.py:2: DtypeWarning: Columns (16,18,19,23,24,25,27,29) have mixed types. Specify dtype option on import or set low_memory=False.
  combined_csv = pd.concat([pd.read_csv(f, encoding="ISO-8859-1") for f in all_filenames ])
C:\Users\joaov\AppData\Local\Temp\ipykernel_13336\2395269944.py:2: DtypeWarning: Columns (7,11,12,16,18,19,21,22,24,25,29,30,31,35,39) have mixed types. Specify dtype option on import or set low_memory=False.
  combined_csv = pd.concat([pd.read_csv(f, encoding="ISO-8859-1") for f in all_filenames ])
C:\Users\joaov\AppData\Local\Temp\ipykernel_13336\2395269944.py:2: DtypeWarning: Columns (7,11,12,16,18,19,21,22,23,24,25,27,28,29,35,39) have mixed types. Specify dtype option on import or set low_memory=False.
  combined_csv = pd.concat([pd.read_csv(f, encoding="ISO-8859-1") for f in all_filenames ])
C:\Users\joaov\AppData\Local\Temp\ipykernel_13336\2395269944.py:2: DtypeWarning: Columns (7,11,12,16,18,19,21,22,23,24,25,27,28,29,35,39) have mixed types. Specify dtype option on import or set low_memory=False.
  combined_csv = pd.concat([pd.read_csv(f, encoding="ISO-8859-1") for f in all_filenames ])
C:\Users\joaov\AppData\Local\Temp\ipykernel_13336\2395269944.py:2: DtypeWarning: Columns (12,16,18,19,20,22,23,24,25,27,28,29,35,39) have mixed types. Specify dtype option on import or set low_memory=False.
  combined_csv = pd.concat([pd.read_csv(f, encoding="ISO-8859-1") for f in all_filenames ])
C:\Users\joaov\AppData\Local\Temp\ipykernel_13336\2395269944.py:2: DtypeWarning: Columns (7,11,12,18,19,21,22,28,29,35,39) have mixed types. Specify dtype option on import or set low_memory=False.
  combined_csv = pd.concat([pd.read_csv(f, encoding="ISO-8859-1") for f in all_filenames ])
C:\Users\joaov\AppData\Local\Temp\ipykernel_13336\2395269944.py:2: DtypeWarning: Columns (7,11,12,16,18,19,21,22,23,24,25,28,29,35,39) have mixed types. Specify dtype option on import or set low_memory=False.
  combined_csv = pd.concat([pd.read_csv(f, encoding="ISO-8859-1") for f in all_filenames ])
C:\Users\joaov\AppData\Local\Temp\ipykernel_13336\2395269944.py:2: DtypeWarning: Columns (7,11,12,16,18,19,20,21,22,23,24,25,27,28,29,30,31,35) have mixed types. Specify dtype option on import or set low_memory=False.
  combined_csv = pd.concat([pd.read_csv(f, encoding="ISO-8859-1") for f in all_filenames ])
C:\Users\joaov\AppData\Local\Temp\ipykernel_13336\2395269944.py:2: DtypeWarning: Columns (16,18,19,21,22,23,25,28,29,39) have mixed types. Specify dtype option on import or set low_memory=False.
  combined_csv = pd.concat([pd.read_csv(f, encoding="ISO-8859-1") for f in all_filenames ])
C:\Users\joaov\AppData\Local\Temp\ipykernel_13336\2395269944.py:2: DtypeWarning: Columns (7,11,12,16,18,19,20,21,22,24,25,27,28,29,35,39) have mixed types. Specify dtype option on import or set low_memory=False.
  combined_csv = pd.concat([pd.read_csv(f, encoding="ISO-8859-1") for f in all_filenames ])
C:\Users\joaov\AppData\Local\Temp\ipykernel_13336\2395269944.py:2: DtypeWarning: Columns (12,16,18,19,22,23,24,25,27,29,35,39) have mixed types. Specify dtype option on import or set low_memory=False.
  combined_csv = pd.concat([pd.read_csv(f, encoding="ISO-8859-1") for f in all_filenames ])
C:\Users\joaov\AppData\Local\Temp\ipykernel_13336\2395269944.py:2: DtypeWarning: Columns (29,39) have mixed types. Specify dtype option on import or set low_memory=False.
  combined_csv = pd.concat([pd.read_csv(f, encoding="ISO-8859-1") for f in all_filenames ])
C:\Users\joaov\AppData\Local\Temp\ipykernel_13336\2395269944.py:2: DtypeWarning: Columns (7,11,12,16,18,19,21,22,23,24,25,27,28,29,35,39) have mixed types. Specify dtype option on import or set low_memory=False.
  combined_csv = pd.concat([pd.read_csv(f, encoding="ISO-8859-1") for f in all_filenames ])
C:\Users\joaov\AppData\Local\Temp\ipykernel_13336\2395269944.py:2: DtypeWarning: Columns (7,11,12,18,19,21,22,28,29,35,39) have mixed types. Specify dtype option on import or set low_memory=False.
  combined_csv = pd.concat([pd.read_csv(f, encoding="ISO-8859-1") for f in all_filenames ])
C:\Users\joaov\AppData\Local\Temp\ipykernel_13336\2395269944.py:2: DtypeWarning: Columns (7,11,12,16,18,19,21,22,24,25,28,29,35,39) have mixed types. Specify dtype option on import or set low_memory=False.
  combined_csv = pd.concat([pd.read_csv(f, encoding="ISO-8859-1") for f in all_filenames ])
C:\Users\joaov\AppData\Local\Temp\ipykernel_13336\2395269944.py:2: DtypeWarning: Columns (7,11,12,16,18,19,21,22,23,24,25,27,28,29,35,39) have mixed types. Specify dtype option on import or set low_memory=False.
  combined_csv = pd.concat([pd.read_csv(f, encoding="ISO-8859-1") for f in all_filenames ])
C:\Users\joaov\AppData\Local\Temp\ipykernel_13336\2395269944.py:2: DtypeWarning: Columns (16,21,25,29) have mixed types. Specify dtype option on import or set low_memory=False.
  combined_csv = pd.concat([pd.read_csv(f, encoding="ISO-8859-1") for f in all_filenames ])
C:\Users\joaov\AppData\Local\Temp\ipykernel_13336\2395269944.py:2: DtypeWarning: Columns (7,11,12,16,18,19,21,22,24,25,28,29,35,39) have mixed types. Specify dtype option on import or set low_memory=False.
  combined_csv = pd.concat([pd.read_csv(f, encoding="ISO-8859-1") for f in all_filenames ])
C:\Users\joaov\AppData\Local\Temp\ipykernel_13336\2395269944.py:2: DtypeWarning: Columns (7,11,12,15,16,18,19,20,21,22,23,24,25,27,28,29,35,39) have mixed types. Specify dtype option on import or set low_memory=False.
  combined_csv = pd.concat([pd.read_csv(f, encoding="ISO-8859-1") for f in all_filenames ])
C:\Users\joaov\AppData\Local\Temp\ipykernel_13336\2395269944.py:2: DtypeWarning: Columns (7,11,12,16,18,19,21,22,23,24,25,27,28,29,30,31,35,39) have mixed types. Specify dtype option on import or set low_memory=False.
  combined_csv = pd.concat([pd.read_csv(f, encoding="ISO-8859-1") for f in all_filenames ])
C:\Users\joaov\AppData\Local\Temp\ipykernel_13336\2395269944.py:2: DtypeWarning: Columns (7,11,12,16,18,19,20,21,22,23,24,25,28,29,35,39) have mixed types. Specify dtype option on import or set low_memory=False.
  combined_csv = pd.concat([pd.read_csv(f, encoding="ISO-8859-1") for f in all_filenames ])

In [5]:
#Transformando FreqTxMHz em float, ele vem como object
combined_csv['FreqTxMHz'] = combined_csv['FreqTxMHz'].astype(float)

In [6]:
#Dataframe resultante
combined_csv

,Status.state,NomeEntidade,NumFistel,NumServico,NumAto,NumEstacao,EnderecoEstacao,EndComplemento,SiglaUf,CodMunicipio,...,Latitude,Longitude,CodDebitoTFI,DataLicenciamento,DataPrimeiroLicenciamento,NumRede,_id,DataValidade,NumFistelAssociado,NomeEntidadeAssociado
0,LIC-LIC-01,TELEFONICA BRASIL S.A.,5.040915e+10,10.0,48412023.0,5202620,RUA DE CATUMBI,NaN,RJ,3304557,...,-22.91667,-43.19444,G,2023-07-05,1999-09-15,NaN,4d5c019f69f36,2038-04-30,NaN,NaN
1,LIC-LIC-01,TELEFONICA BRASIL S.A.,5.040915e+10,10.0,48412023.0,5202620,RUA DE CATUMBI,NaN,RJ,3304557,...,-22.91667,-43.19444,G,2023-07-05,1999-09-15,NaN,4d5c019f69f37,2038-04-30,NaN,NaN
2,LIC-LIC-01,TELEFONICA BRASIL S.A.,5.040915e+10,10.0,48422023.0,5202620,RUA DE CATUMBI,NaN,RJ,3304557,...,-22.91667,-43.19444,G,2023-07-05,1999-09-15,NaN,4d5c019f69f38,2038-04-30,NaN,NaN
3,LIC-LIC-01,TELEFONICA BRASIL S.A.,5.040915e+10,10.0,48422023.0,5202620,RUA DE CATUMBI,NaN,RJ,3304557,...,-22.91667,-43.19444,G,2023-07-05,1999-09-15,NaN,4d5c019f69f39,2038-04-30,NaN,NaN
4,LIC-LIC-01,TELEFONICA BRASIL S.A.,5.040915e+10,10.0,48412023.0,5202620,RUA DE CATUMBI,NaN,RJ,3304557,...,-22.91667,-43.19444,G,2023-07-05,1999-09-15,NaN,4d5c019f69f3a,2038-04-30,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
320847,LIC-LIC-01,TIM S A,5.040943e+10,10.0,48352023.0,693208287,RUA 11,QD 35,MA,2111201,...,-2.555861,-44.185833,G,2023-10-10,2011-02-22,NaN,b67285f80339dc0c,2029-12-08,NaN,NaN
320848,LIC-LIC-01,TIM S A,5.040943e+10,10.0,48352023.0,693208287,RUA 11,QD 35,MA,2111201,...,-2.555861,-44.185833,G,2023-10-10,2011-02-22,NaN,b67285f80339dc0d,2029-12-08,NaN,NaN
320849,LIC-LIC-01,TIM S A,5.040943e+10,10.0,47102015.0,693208287,RUA 11,QD 35,MA,2111201,...,-2.555861,-44.185833,G,2023-10-10,2011-02-22,NaN,b67285f80339dc0e,2029-12-08,NaN,NaN
320850,LIC-LIC-01,TIM S A,5.040943e+10,10.0,47102015.0,693208287,RUA 11,QD 35,MA,2111201,...,-2.555861,-44.185833,G,2023-10-10,2011-02-22,NaN,b67285f80339dc0f,2029-12-08,NaN,NaN
320851,LIC-LIC-01,TIM S A,5.040943e+10,10.0,47102015.0,693208287,RUA 11,QD 35,MA,2111201,...,-2.555861,-44.185833,G,2023-10-10,2011-02-22,NaN,b67285f80339dc10,2029-12-08,NaN,NaN

In [7]:
#Criando a função para calcular a diferencia em quilômetros
def calc_km(lat1,lon1,lat2,lon2):
    try:
        loc1=(lat1,lon1)
        loc2=(lat2,lon2)
        return hs.haversine(loc1,loc2)
    except:
        pass

In [8]:
#DF de torres filtrando LTE (4G) e o estado
df_torres = combined_csv.loc[(combined_csv['Tecnologia'] == 'LTE') & (combined_csv['FreqTxMHz'] >= 758) & (combined_csv['FreqTxMHz'] <= 894) & (combined_csv['SiglaUf'] == 'SP')]
#DF de escolas filtrando o estado
df_escolas = combined_csv.loc[(combined_csv['Tecnologia'] == 'Escola') & (combined_csv['SiglaUf'] == 'SP')]

In [9]:
#Consolidando os dois dataframes para ter 4 colunas (latitude e longitude torre + latitude e longitude escola)
escola_torre_df = df_torres.merge(df_escolas, how='cross')

In [10]:
#Criando a coluna de distância entre a torre a escola usando haversine
escola_torre_df['Distancia KM'] = escola_torre_df.apply(lambda x:calc_km(x['Latitude_x'], x['Longitude_x'],x['Latitude_y'], x['Longitude_y']), axis=1)

In [11]:
#Dataframe pegando a distância mínima por de escola para torre
escola_torre_df_formatado = escola_torre_df.groupby('NomeEntidade_y').agg({'Distancia KM':[min]}).reset_index()

In [12]:
#Criando a flag "Cobertura" onde <= 35km não tem cobertura
escola_torre_df_formatado['Cobertura'] = np.where(escola_torre_df_formatado['Distancia KM'] <= 35, 1, 0)

In [13]:
#Média de cobertura
escola_torre_df_formatado['Cobertura'].mean()

0.8888888888888888

In [14]:
escola_torre_df_formatado

                                       NomeEntidade_y Distancia KM Cobertura
                                                               min
0                     ADOLFO CARDOSO PROF EM-35077033     0.536255         1
1   ANTONIO FERNANDO DOS REIS PREF CRECHE MUNICIPA...     1.033600         1
2              ANTONIO HONORIO DOS SANTOS EM-35654371     9.577595         1
3   APARECIDA DO CARMO MASCHIETTO ESCOLA MUNICIPAL...     0.752130         1
4                   ASSENTAMENTO SANTA CLARA-35925810    13.783326         1
5           AURORA DE ANDRADE CARDOSO EMEIEF-35223104     9.228205         1
6         CASSIANA DOS SANTOS MOREIRA EMEIEF-35664121  4811.830314         0
7         COMUNIDADE NOSSA SENHORA APARECIDA-35911616  2139.890311         0
8    CRECHE MUNICIPAL CANTINHO DO ZEZINHO II-11360200     0.039562         1
9   CRECHE PROFESSORA REGINA CELIA DOS SANTOS-3500...     0.223980         1
10  DAYSE APARECIDA ESPOLAOR TREVISANI EMEIEF-3541...     0.972334         1
11            EM PROFESSORA ELIZABETE XAVIER-35280112     2.574138         1
12           EMEF BAIRRO DA PAINEIRA DE CIMA-35004928    10.240111         1
13           EMEF BAIRRO DA VARGEM DO TANQUE-35004931     9.195129         1
14                      EMEF BAIRRO DO CEDRO-35004921    14.034662         1
15                    EMEF BAIRRO DO SAPEZAL-35004932     0.500863         1
16                       EMEF JOAO CROZARIOL-35273272     1.397410         1
17                     ESCOLA FUGITARO NAGAO-35229684     2.638647         1
18                  FLORINDO JULIANI EMEFEIR-35208164     0.107868         1
19  GERALDA ERNESTINA DA SILVA CRECHE MUNICIPAL-35...     0.721477         1
20        GISSELDA APARECIDA TUROLA PIOVEZAN-35452312     1.817100         1
21           HERVAL BELLUSCI ENGENHEIRO ETEC-35031100     5.107434         1
22                IRENE MACHADO DE LIMA DONA-35901660  2139.890311         0
23                    JAYME PANSANI VER EMEI-35096921     0.217828         1
24                 JOAO PEREIRA LOPES EMEIEF-35664194     1.300750         1
25           JOAQUIM RIBEIRO DE ALMEIDA EMEF-35664133     6.532103         1
26                     JOFRE MANOEL PREFEITO-35908344    15.919541         1
27            JOSE ERMIRIO DE MORAES SENADOR-35040289     6.219367         1
28          JOSE JESUS PAES ESCOLA MUNICIPAL-35281608     2.037870         1
29          JOSE LUIZ VIANA COUTINHO DR ETEC-35910934     2.229569         1
30        JOSE RODRIGUES DE FREITAS VEREADOR-35049815     0.251758         1
31      JOSE TEIXEIRA ROSAS ESCOLA MUNICIPAL-35073325     6.854811         1
32             JULIA DA SILVEIRA MELLO PROFA-35048239     4.058378         1
33                   LUCILIA GROTHE LIBERATO-35049803     2.878734         1
34                             LUIZ PAGLIATO-35043369     5.016008         1
35                 MANUEL JOSE MARTINS EMEIF-35244338  4955.256796         0
36  MARIA BENEDITA RODRIGUES ESCOLA MUNICIPAL-3528...     3.197530         1
37                      MARINA FALSETTI EMEI-35097743     0.760355         1
38          MATHEUS LEITE DE ABREU PROF ETEC-35028721     1.056239         1
39                           Nte Sao Roque-SP00012371     0.268399         1
40                  PASCOAL GRECCO PROFESSOR-35035105     7.523118         1
41                   PAULINA DE MORAIS PROFA-35913571     5.104783         1
42              PROJETO LAGOA SAO PAULO EMEF-35277472     3.684873         1
43  RUTTE RODRIGUES DE CARVALHO PROFESSORA EMEIF-3...     3.820412         1
44         SEBASTIANA AUGUSTA DE MORAES ETEC-35910910     4.996003         1
45                       SITIO DOS MORAES EM-35244090     3.349058         1
46                  SITIO RIBEIRAO BONITO EM-35661272     6.322204         1
47                     SITIO VISTA GRANDE EM-35244089     9.415856         1
48  SYLVIA PORTUGAL GOUVEA DE SYLLOS PROFESSOR A-3...     2.940686         1
49           TANCREDO NEVES CRECHE MUNICIPAL-35099156     2.307258         1
50  THEREZINHA AP VILANI DE CAMARGO PROFA EMEI-350...     0.509182         1
51               TOSHIMARO KACUTA COMENDADOR-35913534     9.768182         1
52  VENERANDA AUGUSTA BERTANHA SOARES PROFESSORA E...   228.174081         0
53                          VILA SAO JOSE EM-35221338   438.377114         0

In [15]:
#Gerando arquivo excel com Escola, quilometragem e Flag Cobertura
#escola_torre_df_formatado.to_excel("Cobertura Escolas PA.xlsx")

In [16]:
#######################################################################################################
#Utilizando base amplimax##############################################################################
#######################################################################################################

In [17]:
#Base Total Amplimax
base_amplimax = pd.read_csv('C:\\Users\\joaov\\Desktop\\Torres Consolidado\\Arquivos Originais\\base_amplimax_coleta_v2.csv', sep=',')

C:\Users\joaov\AppData\Local\Temp\ipykernel_13336\385458704.py:2: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  base_amplimax = pd.read_csv('C:\\Users\\joaov\\Desktop\\Torres Consolidado\\Arquivos Originais\\base_amplimax_coleta_v2.csv', sep=',')

In [157]:
#Base de escolas do estado filtrado
df_escolas_nova = combined_csv.loc[(combined_csv['Tecnologia'] == 'Escola') & (combined_csv['SiglaUf'] == 'DF')]
df_amplimax_nova = base_amplimax.loc[base_amplimax['Estado Cliente'] == 'DF']

In [158]:
#Merge das duas bases
amplimax_escolas = df_amplimax_nova.merge(df_escolas_nova, how='cross')

In [159]:
#Criando a coluna de distância entre a torre a escola usando haversine
amplimax_escolas['Distancia KM'] = amplimax_escolas.apply(lambda x:calc_km(x['Latitude GPS'], x['Longitude GPS'],x['Latitude'], x['Longitude']), axis=1)

In [160]:
#Dataframe pegando a distância mínima por de escola para torre
amplimax_escolas_formatado = amplimax_escolas.groupby('NomeEntidade').agg({'Distancia KM':[min]}).reset_index()

In [161]:
amplimax_escolas_formatado.to_excel("Cobertura Amplimax DF.xlsx")